predictdb:
  path: '/vol/bmd/yanyul/data/predictdb_models/ctimp_Whole_Blood.db'
  name: 'ctimp_Whole_Blood'
  varcol: 'rsid'
genotype:
  bgen: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb_imp_chr{i}_v3.bgen'
  sample: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb19526_imp_chr1_v3_s487395.sample'
indiv_path: '/vol/bmd/yanyul/GitHub/ptrs-ukb/output/data_split/{population}.txt'
indiv_name: 'Chinese'
plink_cmd: '/vol/bmd/yanyul/softwares/plink2'
plink_memory_in_mb: 5000
  
