indiv_list: '/scratch/t.cri.yliang/PTRS/output/data_split/British-test-{num}.txt,/scratch/t.cri.yliang/PTRS/output/data_split/British-validation-{num}.txt,/scratch/t.cri.yliang/PTRS/output/data_split/African.txt,/scratch/t.cri.yliang/PTRS/output/data_split/Chinese.txt,/scratch/t.cri.yliang/PTRS/output/data_split/Indian.txt'
phenotype: 
  table: '/scratch/t.cri.yliang/PTRS/output/query_phenotypes_cleaned_up.csv'
  yaml: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/ptrs-ukb/misc/gwas_full_pheno_covar.yaml'
indiv_col: 's'
prs: '/scratch/t.cri.yliang/PTRS/prs/prs_gcp_subset{num}.tsv.bgz'
