variant_list: ''
individual_list: ''
bgen: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb_imp_chr{chr_num}_v3.bgen'
sample: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb19526_imp_chr1_v3_s487395.sample'
chr_num: 22
plink2_path: '/vol/bmd/yanyul/softwares/plink2'
