predictdb: '/vol/bmd/yanyul/data/predictdb_models/{model}.db'
genotype:
  bgen: '/homes/yanyul/test3.bgen'  # '/vol/bmd/data/ukbiobank/genotypes/v3/ukb_imp_chr{i}_v3.bgen'
  sample: '/homes/yanyul/test3.sample'  # '/vol/bmd/data/ukbiobank/genotypes/v3/ukb19526_imp_chr1_v3_s487395.sample'
  name: 'ukb_imp'
predictdb_name: 'ctimp_Whole_Blood'  
bgens_cache_nvar: 250
bgens_writing_cache_in_mb: 500
script_dir: '/homes/yanyul/labshare/softwares/from_github/predixcan_prediction'
bgenix_dir: '/vol/bmd/yanyul/softwares/from_bitbucket/gavinband-bgen-4e33223a8dc4/build/apps'
