# predicted expression
pred_expr: '/vol/bmd/yanyul/UKB/predicted_expression/predicted_expression.ukb_imp_x_{gene_model}.h5'
gene_model_list: 
  - 'ctimp_Whole_Blood'
  - 'ctimp_Muscle_Skeletal'
gene_model_list_name: 'ctimp'
mode: 'naive'
  

# individual list
indiv_list: '/vol/bmd/yanyul/GitHub/ptrs-ukb/output/data_split/{pop_name}.txt'
pop_name: 'British-test-1'

# phenotypes and covariates table
pheno_covar:
  table: '/vol/bmd/yanyul/GitHub/ptrs-ukb/output/query_phenotypes_cleaned_up.csv'
  yaml: '/vol/bmd/yanyul/GitHub/ptrs-ukb/misc/gwas_full_pheno_covar.yaml'
table_name: 'martin_et_al_traits'

# gcta binary path
gcta_path: '/vol/bmd/yanyul/softwares/gcta_1.93.0beta/gcta64'