predictdb:
  model: '/gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/models_v1/eqtl/mashr/mashr_{tissue}.db'
  covariance: '/gpfs/data/im-lab/nas40t2/abarbeira/projects/gtex_v8/models_v1/eqtl/mashr/mashr_{tissue}.txt.gz'
  name: 'mashr'
gwas:
  snp-name-col: 'new_id'
  effect-allele-col: 'alt'
  non-effect-allele-col: 'ref'
  effect_size_inputs:
    beta_column: 'beta'
    se_column: 'se'
  extra_cmd: '--keep_non_rsid  --model_db_snp_key varID'

# gwas_name: 'subset1_x_height'
gwas_path: '/scratch/t.cri.yliang/PTRS/gwas_table_annot_with_gtexv8/annot_with_gtexid.{gwas_name}.tsv.gz'

tissue: 'Whole_Blood'
metaxcan-path: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/MetaXcan/software'

outdir: '/scratch/t.cri.yliang/PTRS/spredixcan_mashr'

